# Generated by Django 4.1.4 on 2022-12-23 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='genre',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
